#! /bin/bash -ex
cd $(dirname $0)/..

aws cloudformation deploy \
    --stack-name aws-training-yutingli-lambda-bucket \
    --template-file configs/lambda-bucket.yml \
    --capabilities CAPABILITY_NAMED_IAM \
    --no-fail-on-empty-changeset \
    --profile aws-training-profile \
    --region ap-southeast-1
