#! /bin/bash -ex
cd $(dirname $0)/..

aws events put-rule \
    --name yuting-lambda-scheduled-rule \
    --schedule-expression 'rate(60 minutes)' \
    --profile aws-training-profile \
    --region ap-southeast-1
